
version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/node

    steps:
      
      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Newman
          command: 'sudo npm install -g newman'

      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: API Testing for GIVE20
          command: 'newman run --disable-unicode collections/GIVEB-20_9March2018.json --environment collections/env_variable_GIVE20.json'

      