
version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: postman/newman_ubuntu1404:3.9.2

    steps:
      
      
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up

            

      
